// src/adapter/verifyReviews.mjs
// Verify/UAT/validation/patterns/security/reviews methods. Phase 10 / IMPL-04.

const NOT_IMPLEMENTED = (name) => {
  throw new Error('BeadsAdapter.' + name + ': not implemented (Phase 10 / IMPL-04)');
};

export default {
  async getVerification(phase)               { NOT_IMPLEMENTED('getVerification'); },
  async getVerificationStatus(phase)         { NOT_IMPLEMENTED('getVerificationStatus'); },
  async recordVerification(phase, report)    { NOT_IMPLEMENTED('recordVerification'); },
  async listVerificationsAcrossPhases()      { NOT_IMPLEMENTED('listVerificationsAcrossPhases'); },
  async getUat(phase)                        { NOT_IMPLEMENTED('getUat'); },
  async listActiveUat()                      { NOT_IMPLEMENTED('listActiveUat'); },
  async listOutstandingUat()                 { NOT_IMPLEMENTED('listOutstandingUat'); },
  async createUat(phase, spec)               { NOT_IMPLEMENTED('createUat'); },
  async updateUat(phase, patch)              { NOT_IMPLEMENTED('updateUat'); },
  async updateUatGap(phase, gap)             { NOT_IMPLEMENTED('updateUatGap'); },
  async updateUatStatus(phase, status)       { NOT_IMPLEMENTED('updateUatStatus'); },
  async updateUatGapDiagnoses(phase, diagnoses) { NOT_IMPLEMENTED('updateUatGapDiagnoses'); },
  async getValidation(phase)                 { NOT_IMPLEMENTED('getValidation'); },
  async recordValidation(phase, report)      { NOT_IMPLEMENTED('recordValidation'); },
  async appendValidationAudit(phase, audit)  { NOT_IMPLEMENTED('appendValidationAudit'); },
  async recordPatterns(phase, patterns)      { NOT_IMPLEMENTED('recordPatterns'); },
  async getSecurity(phase)                   { NOT_IMPLEMENTED('getSecurity'); },
  async putSecurity(phase, body)             { NOT_IMPLEMENTED('putSecurity'); },
  async updateSecurityAuditTrail(phase, audit) { NOT_IMPLEMENTED('updateSecurityAuditTrail'); },
  async getThreatRegister(phase)             { NOT_IMPLEMENTED('getThreatRegister'); },
  async getReview(phase, kind)               { NOT_IMPLEMENTED('getReview'); },
  async addReview(phase, kind, body)         { NOT_IMPLEMENTED('addReview'); },
  async getReviewFix(phase, kind)            { NOT_IMPLEMENTED('getReviewFix'); },
  async addReviewFix(phase, kind, body)      { NOT_IMPLEMENTED('addReviewFix'); },
  async archiveReviewIteration(phase, kind, iteration) { NOT_IMPLEMENTED('archiveReviewIteration'); },
  async getUiSpec(phase)                     { NOT_IMPLEMENTED('getUiSpec'); },
  async addUiSpec(phase, body)               { NOT_IMPLEMENTED('addUiSpec'); },
  async getUiReview(phase)                   { NOT_IMPLEMENTED('getUiReview'); },
  async addUiReview(phase, body)             { NOT_IMPLEMENTED('addUiReview'); },
  async addUiReviewScreenshot(phase, screenshot) { NOT_IMPLEMENTED('addUiReviewScreenshot'); },
  async getEvalReview(phase)                 { NOT_IMPLEMENTED('getEvalReview'); },
  async addEvalReview(phase, body)           { NOT_IMPLEMENTED('addEvalReview'); },
  async getAiSpec(phase)                     { NOT_IMPLEMENTED('getAiSpec'); },
  async putAiSpec(phase, body)               { NOT_IMPLEMENTED('putAiSpec'); },
  async getAiSpecTemplate()                  { NOT_IMPLEMENTED('getAiSpecTemplate'); },
  async validateAiSpec(phase)                { NOT_IMPLEMENTED('validateAiSpec'); },
  async updateAiSpecSection(phase, sectionId, body) { NOT_IMPLEMENTED('updateAiSpecSection'); },
  async getReviews(phase)                    { NOT_IMPLEMENTED('getReviews'); },
  async addReviews(phase, body)              { NOT_IMPLEMENTED('addReviews'); },
  async recordDocVerification(phase, doc)    { NOT_IMPLEMENTED('recordDocVerification'); },
  async verifyPlanArtifacts(phase, plan)     { NOT_IMPLEMENTED('verifyPlanArtifacts'); },
  async verifySummary(phase, plan)           { NOT_IMPLEMENTED('verifySummary'); },
  async checkDecisionCoveragePlan(phase, plan) { NOT_IMPLEMENTED('checkDecisionCoveragePlan'); },
  async checkDecisionCoverageVerify(phase)   { NOT_IMPLEMENTED('checkDecisionCoverageVerify'); },
  async getPhaseCompletion(phase)            { NOT_IMPLEMENTED('getPhaseCompletion'); },
  async listSafetyGates()                    { NOT_IMPLEMENTED('listSafetyGates'); },
  async routeNextAction(context)             { NOT_IMPLEMENTED('routeNextAction'); },
  async detectPhaseType(phase)               { NOT_IMPLEMENTED('detectPhaseType'); },
  async getAutoMode()                        { NOT_IMPLEMENTED('getAutoMode'); },
  async getConfigGates()                     { NOT_IMPLEMENTED('getConfigGates'); },
};
