#!/usr/bin/env bash
# Regenerate .planning/STATE.md from worktree-local milestone source.
#
# Source of truth: git config --worktree gsd-beads.milestone (worktree-local)
#   + ${GSD_MILESTONE:-} env override (for tests)
# Output: .planning/STATE.md (written atomically via tmp file + mv)
#
# D-05: STATE.md is parameterized by the worktree, NOT bd. Two worktrees on
# different milestones see different STATE.md content while sharing one bd
# store. Milestone-FILTERING of bd state for content (e.g., "show me only
# v0.2 phases") lands in Phases 5+ where progress.* / state.* read handlers
# ship.
#
# Idempotency: byte-stable output for unchanged milestone value.
# T-04-14 mitigation: only writes to .planning/STATE.md.
#
# Stack: bash + git CLI only. No bd, no jq.
set -euo pipefail

# --- BEGIN GSD-BEADS LOCK PREAMBLE v1 ---
# Resolve source repo's .beads/ from any worktree, absolutize via cd+pwd -P.
common=$(git rev-parse --git-common-dir 2>/dev/null) || common="$PWD/.git"
source_root="$(dirname "$(cd "$common" && pwd -P)")"
LOCK="$source_root/.beads/.gsd-beads.lock"

# Pre-flight: flock present? (Pitfall 1 — macOS users must brew install flock)
if ! command -v flock >/dev/null 2>&1; then
  echo "[gsd-beads] ERROR: flock not installed (macOS: brew install flock)" >&2
  exit 1
fi

# Lazy-create lock file (zero bytes, never deleted; *.lock is already in .beads/.gitignore).
mkdir -p "$(dirname "$LOCK")"
[ -e "$LOCK" ] || : > "$LOCK"

# Acquire exclusive lock (30s timeout matches bd-sync.sh hook timeout in settings.fragment.json).
exec 9>"$LOCK"
if ! flock -x -w 30 9; then
  echo "[gsd-beads] another regen is in progress at $LOCK — retry shortly" >&2
  exit 1
fi
# Lock auto-released when fd 9 closes (script exit).
# --- END GSD-BEADS LOCK PREAMBLE v1 ---

# ---------------------------------------------------------------------------
# Pre-flight: locate project root (verbatim from regen-roadmap.sh:44-50)
# ---------------------------------------------------------------------------
if root=$(git rev-parse --show-toplevel 2>/dev/null); then
  : # git root found
elif [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
  root="$CLAUDE_PROJECT_DIR"
else
  root="$PWD"
fi

# ---------------------------------------------------------------------------
# Read worktree-local milestone source (D-05).
# `git config --worktree` returns empty + non-zero when the key is unset.
# Fallback: ${GSD_MILESTONE:-} env override (for tests). Final fallback: "(unset)".
# ---------------------------------------------------------------------------
milestone=$(git config --worktree gsd-beads.milestone 2>/dev/null || true)
[ -z "$milestone" ] && milestone="${GSD_MILESTONE:-}"
[ -z "$milestone" ] && milestone="(unset)"

OUT="$root/.planning/STATE.md"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

mkdir -p "$(dirname "$OUT")"

# ---------------------------------------------------------------------------
# Build STATE.md content. Minimal for Phase 4 — Phases 6-7 expand to include
# bd-derived progress + decisions filtered by milestone. The milestone label
# is included verbatim so milestone-scoping tests can grep for it.
# ---------------------------------------------------------------------------
{
  printf -- "---\n"
  printf -- "gsd_state_version: 1.0\n"
  printf -- "milestone: %s\n" "$milestone"
  printf -- "---\n"
  printf -- "\n"
  printf -- "# Project State\n"
  printf -- "\n"
  printf -- "**Current milestone:** %s\n" "$milestone"
  printf -- "\n"
  printf -- "(Generated by scripts/regen-state.sh — do not edit by hand.)\n"
} > "$tmp"

# ---------------------------------------------------------------------------
# Atomic write: mv tmp → .planning/STATE.md
# ---------------------------------------------------------------------------
mv "$tmp" "$OUT"
trap - EXIT
